<?php
return [
    [
        "boss_name" => "Butcher",
        "img" => "bosses/butcher.webp",
        "release_date" => "22-02-2018",
        "is_wild_target" => false,
        "summary" => "The documentation is clearly unreliable. As we piece together the puzzle, we are forced to make many leaps of both logic and faith. Inconsistencies are not altogether surprising considering the sources, and the subjectivity of remembered experience. The big picture makes a certain kind of sense, follows its own internal logic. In spite of that, even I have trouble believing what I've found in regards to its first appearance in Louisiana. The huge bloated body - clearly a relative of the Meathead - with bits of wood and metal protruding from the skin. A leather apron covers the horrors of its torso, the head of a pig,and - and somehow this is the detail that I find most difficult to believe - a flaming hook. It is comfortable with fire and resistant to heat - likely thanks in part to the apron - and to bludgeoning. A regular bulletsponge, and though more fallible to rending attacks, it is hard for me to imagine how these people managed to kill any of them at all. When driven into a violent fury, its behavior would become erratic, and flames would fly from the aforementioned hook. I shudder to think. What it must have felt like to round a dark corner and come face to face with the empty eyes and glowing hook of that seemingly impossible beast? If the reports can be believed, these Butchers, as they were called by those who hunted them, were the stuff of nightmares. Either that, or only the most fantastical of tales have survived. Can we really separate the facts from the fictions at this distance? Perhaps not, but I am driven to continue to try, even if I never can be sure of the truth."
    ],
    [
        "boss_name" => "Spider",
        "img" => "bosses/spider.webp",
        "release_date" => "22-02-2018",
        "is_wild_target" => false,
        "summary" => "More people than you think suffer arachnophobia. A primal fear of something poisonous lurking, weaving traps, able to scale any surface. At odds, though, with its domestic function: keeping a dwelling clear of flies and other undesirable creatures. A spider the size of a quarter, though, is manageable. But, at the size of a horse, even the most rational and logical would recoil in disgust at an eight-legged arachnid, gnashing its mandibles, expelling coils of webbing.The Spider strikes the ardent occultist as one of the most outlandish and monstrous examples of the hysteria that so gripped the bayous. An example, though, that in all its multifaceted dimensions and exhaustive iterations, vindicates that hysteria. References keep cropping up throughout the archive, of something not quite human and not quite spider, a semi-sentient mass of limbs, poisonous in both body and intent. The hunters were pragmatic, that much can be said. Most information preserved concerned how to combat such a beast. It hit hard, then retreated to the shadows to ready its next assault. Hunters were advised to keep moving, as the Spider could apparently spit poison, which lingered some time after in the air. Melee weapons, which could slash or pummel, proved effective at rending its limbs and breaking its bones. Poison and other toxins were ineffective. I'm sure that a more fastidious study of the source text would doubtless reveal more insights. The best sources I found to work with though were interviews given by the notorious JV. A detailed physical description, and at least reference to Black and Scognamiglio (the latter suspiciously silent on the subject in his own writing). Some pages missing, though the most relevant are reproduced here. What is known though, is that this Spider was of the greater possessions of the greater evil that lurked there. All the more that can be discovered of it, the more clearly we will see the picture as a whole. "
    ],
    [
        "boss_name" => "Assassin",
        "img" => "bosses/assassin.webp",
        "release_date" => "29-03-2019",
        "is_wild_target" => false,
        "summary" => "The arrival of the Assassin marks a surprising turning point in the Louisiana Case. Before its arrival, the entity's major aspects were certainly formidable combatants, though designed for other purposes. The humanoid Assassin seemed especially sculpted to shock humans, and destroy them. Accounts of such a creature are similar: that of a tall humanoid figure who can seemingly melt into a swarm of insects. Whether or not this is the result of trickery, or actual physical transformation, is debatable. Though with all things relating to this case, I am inclined toward belief in the most outlandish and bizarre theorizations one day, and incredulous the next. Of this, I've noted a remarkable pattern in its behavior. The Assassin seemed capable of remarkable feats. Chief among them, the ability to split into several (three) manifestations of itself. These manifestations would function as a distraction, attacking hunters independently, while the true Assassin would use the opportunity to find the right moment to strike. Thankfully, Harold Black preserved much of what we know. His encounter with the Assassin seems to have forged him into the man we revere today. His account, in typical Blackian fashion, seems indirect by modern academic standards. Indeed, he does mention his failed career as a writer, and his inability to inform clearly seems to affirm this. However, this does give a rare insight into the abilities of the Assassin, particularly their development from a human host. You'd be forgiven for missing some of the more pragmatic information, such as that the Assassin's chest seems to harbor a vulnerable point."
    ],
    [
        "boss_name" => "Scrapbeak",
        "img" => "bosses/scrapbeak.webp",
        "release_date" => "24-03-2021",
        "is_wild_target" => false,
        "summary" => "The question of the beak is paramount. Initially, I had supposed it a mask, fashioned from the scavenged detritus the creature holds so dear, a theory supported by the fact that the beak's composition does not resemble that of any bird yet catalogued by man. However, dissection reveals that the periphery of the beak-structure is fused with the bone of the skull, though the mandibles and the surrounding musculature are curiously positioned, non-functional, and show extensive scarring. The scar tissue is singular, exhibiting attributes of both keloid and hypertrophic tissue, and marked in such a way as to suggest a violently expediated healing process. From this, I must conclude that the beak was not part of the beast's original physiognomy, but rather a more recent addition — an addition that could only have been made through a most gruesome surgical procedure — and that the healing process was accelerated and warped by the transformation process of which I still, maddeningly, know so little. I shudder to think of it, for I can imagine no circumstance under which a man might agree, of his own free will, to allow such a surgery to take place, or the physician willing to perform it. Finding that physician - possibly under the influence of the corruption themselves - would give the most valuable insight into this creature. Perhaps the Sculptor is not, in the end, the most egregious being in the Bayou. One must only read the headlines of the daily papers to know the staggering capacity for cruelty of the human specimen."
    ],
    [
        "boss_name" => "Rotjaw",
        "img" => "bosses/rotjaw.webp",
        "release_date" => "28-06-2023",
        "is_wild_target" => true,
        "summary" => "Rotjaw, as we call this female alligator specimen, defies the physiology of any known aquatic reptile, or creature descended from 'living' taxonomical orders. Putrefaction has encompassed her skull, leaving it bare and smooth. The jaws instill in one a paleolithic fear, something felt by the first mammals to witness their parents eviscerated by reptiles. They are easily capable of crushing three men. Unlike other Boss Targets, Rotjaw cannot be found in a compound. Instead, she guards her water territories out in the open, lying in wait for prey to approach. Find and defeat her to earn a Bounty Token. You'll deserve it as Rotjaw is one of our deadliest enemies yet."
    ],
    [
        "boss_name" => "Hellborn",
        "img" => "bosses/hellborn.jpg",
        "release_date" => "15-08-2024",
        "is_wild_target" => true,
        "summary" => "Hunt is always evolving with new creatures and supernatural horrors roaming the world, and Mammon's Gulch is no exception... Introducing the Hellborn, Hunt's brand-new Wild Target! An amalgam of fire and flesh, a source of immense heat spilling forth from the oil wells below the mountain, this fiery new threat poses a whole new challenge to daring Hunters. Wild Targets are large enemies that drop one Bounty Token when defeated and can be found in various places around the map. Players will find the Hellborn in Mammon's Gulch map only for now. To track down Hellborn, Hunters will need to activate Dark Sight and listen for the creature's signature raging howls. Be prepared - the moment you come across him, Hellborn will unleash an onslaught of fiery attacks, forcing players will need to evade raining fireballs, keep their cool and not become an ash heap…. If defeated the Hellborn will release a deafening screech and drop a Bounty Token & Burn Token with no banish time, so players will need to act fast once he is downed."
    ]
];
