<?php
return [
    [
        "name" => "Ammo Box",
        "img" => "",
        "consumable_type_id" => 1,
        "light_melee_dmg" => 31,
        "heavy_melee_dmg" => 90,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 65,
        "summary" => "This small portable Ammo Box partially refills your weapons' extra ammunition, including special ammunition types."
    ],
    [
        "name" => "Tool Box",
        "img" => "",
        "consumable_type_id" => 1,
        "light_melee_dmg" => 31,
        "heavy_melee_dmg" => 90,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 70,
        "summary" => "A portable toolkit that refills some dwindling supplies in a tight spot."
    ],
    [
        "name" => "Dynamite Stick",
        "img" => "",
        "consumable_type_id" => 2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 750,
        "effect_radius" => 10,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 4,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 18,
        "summary" => "A dynamite stick that detonates with a massive blast after four seconds."
    ],
    [
        "name" => "Waxed Dynamite Stick",
        "img" => "",
        "consumable_type_id" => 2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 750,
        "effect_radius" => 10,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 4,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 18,
        "summary" => "A dynamite stick with a modified powder fuse that enables detonation under water and in choke bomb clouds."
    ],
    [
        "name" => "Dynamite Bundle",
        "img" => "",
        "consumable_type_id" => 2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 1500,
        "effect_radius" => 10,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 4,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 75,
        "summary" => "A bundle of several dynamite sticks. Why only bring one?"
    ],
    [
        "name" => "Big Dynamite Bundle",
        "img" => "",
        "consumable_type_id" => 2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 3000,
        "effect_radius" => 11,
        "effect_duration" => null,
        "throw_range" => 15,
        "fuse_timer" => 4,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 110,
        "summary" => "A bundle of many dynamite sticks. When something really needs to be blown up."
    ],
    [
        "name" => "Sticky Bomb",
        "img" => "",
        "consumable_type_id" => 2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 800,
        "effect_radius" => 22,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 8,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 64,
        "summary" => "Dynamite charge in a sticky frame that can be attached to objects and enemies. Its eight-second fuse doubles the detonation time of a dynamite stick."
    ],
    [
        "name" => "Choke Beetle",
        "img" => "",
        "consumable_type_id" => 3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 1,
        "effect_radius" => 3,
        "effect_duration" => 60,
        "throw_range" => 15,
        "fuse_timer" => null,
        "control_range" => 150,
        "damage_per_tick" => null,
        "cost" => 22,
        "summary" => "Choke Beetles are bred to hunt and track prey, giving Hunters a view from above. They have evolved to explode into a cloud of suffocating gas, which they themselves are immune to."
    ],
    [
        "name" => "Fire Beetle",
        "img" => "",
        "consumable_type_id" => 3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 26,
        "effect_radius" => 2,
        "effect_duration" => null,
        "throw_range" => 15,
        "fuse_timer" => null,
        "control_range" => 150,
        "damage_per_tick" => null,
        "cost" => 57,
        "summary" => "Fire Beetles are bred to find and track pey, giving hunters a view from above. Upon death or command, they will burst into flames that burn everything they touch."
    ],
    [
        "name" => "Stalker Beetle",
        "img" => "",
        "consumable_type_id" => 3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 25,
        "effect_radius" => 5,
        "effect_duration" => null,
        "throw_range" => 15,
        "fuse_timer" => null,
        "control_range" => 150,
        "damage_per_tick" => null,
        "cost" => 45,
        "summary" => "Stalker Beetles are bred to hunt and track prey, giving hunters a view from above. As a last resort, they can sacrifice themselves to cause a small explosion hampering anything caught in the radius."
    ],
    [
        "name" => "Chaos Bomb",
        "img" => "",
        "consumable_type_id" => 4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 8,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 15,
        "summary" => "A set of firecrackers that can be used to temporarily distract nearby enemies. Duration of about 30 seconds."
    ],
    [
        "name" => "Concertina Bomb",
        "img" => "",
        "consumable_type_id" => 5,
        "light_melee_dmg" => 52,
        "heavy_melee_dmg" => 112,
        "damage" => 158,
        "effect_radius" => 7,
        "effect_duration" => null,
        "throw_range" => 15,
        "fuse_timer" => 8,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 48,
        "summary" => "Spring-loaded razorwire coil that unfolds violently when thrown. Shreds and entangles anything that tries to move through."
    ],
    [
        "name" => "Fire Bomb",
        "img" => "",
        "consumable_type_id" => 6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => 3,
        "effect_duration" => 120,
        "throw_range" => 22,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 30,
        "summary" => "Flammable liquid in a glass container that bursts on impact. Spreads burning liquid over a large area."
    ],
    [
        "name" => "Liquid Fire Bomb",
        "img" => "",
        "consumable_type_id" => 6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 11,
        "effect_radius" => 3,
        "effect_duration" => 120,
        "throw_range" => 22,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 35,
        "summary" => "Flammable liquid in a glass container. Burns on the surface of water. Internal steel balls cause it to burst on impact."
    ],
    [
        "name" => "Hellfire Bomb",
        "img" => "",
        "consumable_type_id" => 6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 50,
        "effect_radius" => 6,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 70,
        "summary" => "Flammable liquid in a glass container that bursts on impact and creates a massive fireball."
    ],
    [
        "name" => "Flash Bomb",
        "img" => "",
        "consumable_type_id" => 5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 1,
        "effect_radius" => 8,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 25,
        "summary" => "Light bomb that requires a short priming for its mercury based chemical reaction. The explosion is capable of blinding all in close proximity, even if their eyes are shielded or averted. Needs a short time to be prepared."
    ],
    [
        "name" => "Frag Bomb",
        "img" => "",
        "consumable_type_id" => 2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => 250,
        "effect_radius" => 11,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 4,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 103,
        "summary" => "Frag bombs send lethal shrapnel over a large area, lacerating nearby enemies. unlike dynamite however, the blast is not strong enough to destroy doors or concertina wire."
    ],
    [
        "name" => "Hive Bomb",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 30,
        "throw_range" => 22,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => 4,
        "cost" => 40,
        "summary" => "Poisonous wasps emerge from this bomb to terrorize anyone unfortunate enough to be in the area. However it has no effect on monsters."
    ],
    [
        "name" => "Poison Bomb",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => 3,
        "effect_duration" => 510,
        "throw_range" => 22,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => 6,
        "cost" => 25,
        "summary" => "On detonation emits a persistant, deadly cloud. Anything caught in or that passes through the cloud will be poisoned."
    ],
    [
        "name" => "Medical Pack",
        "img" => "",
        "consumable_type_id" => 8,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 35,
        "summary" => "A portable medical kit that heals 100 health. Deployable in active health emergencies."
    ],
    [
        "name" => "Antidote Shot (Weak)",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 300,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 30,
        "summary" => "Instantly cures and prevents all poison effects. Physical damage associated with poison attacks still applies."
    ],
    [
        "name" => "Antidote Shot",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 600,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 55,
        "summary" => "Instantly cures and prevents all poison effects. Physical damage associated with poison attacks still applies."
    ],
    [
        "name" => "Vitality Shot (Weak)",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 20,
        "summary" => "A shot which immediately restores 75 health."
    ],
    [
        "name" => "Vitality Shot",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 85,
        "summary" => "A shot which immediately restores all health."
    ],
    [
        "name" => "Regeneration Shot (Weak)",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 300,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 40,
        "summary" => "A shot that continually restores health over a short duration."
    ],
    [
        "name" => "Regeneration Shot",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 600,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 105,
        "summary" => "A shot that continually restores health over a short duration."
    ],
    [
        "name" => "Stamina Shot (Weak)",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 300,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 60,
        "summary" => "A shot which immediately restores all stamina and stops further depletion for 5 minutes."
    ],
    [
        "name" => "Stamina Shot",
        "img" => "",
        "consumable_type_id" => 7,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "damage" => null,
        "effect_radius" => null,
        "effect_duration" => 600,
        "throw_range" => null,
        "fuse_timer" => null,
        "control_range" => null,
        "damage_per_tick" => null,
        "cost" => 100,
        "summary" => "A shot which immediately restores all stamina and stops further depletion for 10 minutes."
    ],
];
