<?php
return [
    [
        "tool_name" => "Alert Trip Mine",
        "tool_img" => "",
        "tool_type_id" => 1,
        "capacity" => 4,
        "damage" => 25,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 30,
        "summary" => "This portable tripwire mine releases firecrackers and a small flare, alerting others to its location. Can be use to set hunters or barrels on fire. Comes in a pack of four."
    ],
    [
        "tool_name" => "Blank Fire Decoys",
        "tool_img" => "",
        "tool_type_id" => 1,
        "capacity" => 6,
        "damage" => 20,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 45,
        "summary" => "A decoy that imitates the sound of a gunshot on impact. Useful to distract and confuse enemies."
    ],
    [
        "tool_name" => "Choke Bomb",
        "tool_img" => "",
        "tool_type_id" => 2,
        "capacity" => 2,
        "damage" => 1,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => 3,
        "effect_duration" => 60,
        "throw_range" => 22,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 25,
        "summary" => "The Choke Bomb exudes a gas that extinguishes any flames within its radius while active-as well as preventing new fires from being lit-and induces heavy coughing. Comes in a pack of two."
    ],
    [
        "tool_name" => "Concertina Trip Mine",
        "tool_img" => "",
        "tool_type_id" => 3,
        "capacity" => 2,
        "damage" => 32,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => 2,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 90,
        "summary" => "This portable tripwire mine deploys a small concertina bundle perfect for blocking doors and windows. Comes in a pack of two."
    ],
    [
        "tool_name" => "Decoy Fuses",
        "tool_img" => "",
        "tool_type_id" => 1,
        "capacity" => 3,
        "damage" => 40,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => 6,
        "effective_range" => null,
        "cost" => 30,
        "summary" => "Pack of decoy fuses that can be used to breach closed doors and window shutters. It can also imitate the behavior of a lit bomb and can fool your enemies in clearing a space."
    ],
    [
        "tool_name" => "Decoys",
        "tool_img" => "",
        "tool_type_id" => 1,
        "capacity" => 12,
        "damage" => 20,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => 22,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 6,
        "summary" => "A bag of scrap metal and glass. When thrown the noise can be effectively used to distract or divert enemies."
    ],
    [
        "tool_name" => "Dusters",
        "tool_img" => "",
        "tool_type_id" => 5,
        "capacity" => 1,
        "damage" => 31,
        "light_melee_dmg" => 31,
        "heavy_melee_dmg" => 72,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 30,
        "summary" => "A row of metal rings worn on the hand in order to increase the damage caused in hand-to-hand combat."
    ],
    [
        "tool_name" => "Quad Derringer",
        "tool_img" => "",
        "tool_type_id" => 4,
        "capacity" => 16,
        "damage" => 74,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => 6,
        "cost" => 30,
        "summary" => "A small, light pistol that is easy to carry and conceal. Holds four shots. Twelve additional rounds carried."
    ],
    [
        "tool_name" => "Derringer Pennyshot",
        "tool_img" => "",
        "tool_type_id" => 4,
        "capacity" => 4,
        "damage" => 21,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => 6,
        "cost" => 63,
        "summary" => "A small, light pistol tool that holds two Penny Shot Ammo rounds. Perfect in a pinch."
    ],
    [
        "tool_name" => "First Aid Kit",
        "tool_img" => "",
        "tool_type_id" => 7,
        "capacity" => 3,
        "damage" => null,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => null,
        "cost" => 30,
        "summary" => "A bag of medical supplies that heal 50 health and stop bleeding. Can be used three times."
    ],
    [
        "tool_name" => "Flare Pistol",
        "tool_img" => "",
        "tool_type_id" => 7,
        "capacity" => 3,
        "damage" => 26,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "effect_radius" => null,
        "effect_duration" => null,
        "throw_range" => null,
        "fuse_timer" => null,
        "effective_range" => 18,
        "cost" => 36,
        "summary" => "A bag of medical supplies that heal 50 health and stop bleeding. Can be used three times."
    ],
];
