<?php
return [
    [
        "variant_name" => "Romero 77 Handcannon",
        "slot_id" => 2,
        "damage" => 165,
        "variant_img" => "",
        "ammo_reserve" => 11,
        "bullet_speed" => 375,
        "sway" => 133,
        "effective_range" => 11,
        "reload_time" => 3.5,
        "cycle_time" => 4.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 26,
        "summary" => "The Romero 77 Handcannon is a sawn-off break-action single barrel shotgun. Easier to handle in tight spaces. Less accurate over long range."
    ],
    [
        "variant_name" => "Romero 77 Hatchet",
        "slot_id" => 2,
        "damage" => 145,
        "variant_img" => "",
        "ammo_reserve" => 11,
        "bullet_speed" => 375,
        "sway" => 133,
        "effective_range" => 11,
        "reload_time" => 3.5,
        "cycle_time" => 4.4,
        "light_melee_dmg" => 90,
        "heavy_melee_dmg" => 150,
        "cost" => 62,
        "summary" => "The Romero 77 Hatchet is a sawn-off break-action single barrel shotgun. Easier to handle in tight spaces. Less accurate over long range. Hatchet causes rending damage."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Obrez",
        "slot_id" => 2,
        "damage" => 133,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 133,
        "effective_range" => 314,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 26,
        "cost" => 290,
        "summary" => "Sawn-off variant of the Mosin-Nagant bolt-action rifle. Can be carried as a backup weapon that packs a punch, but without a stock its recoil is brutal."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Obrez Drum",
        "slot_id" => 2,
        "damage" => 133,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 133,
        "effective_range" => 314,
        "reload_time" => 8,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 26,
        "cost" => 350,
        "summary" => "This shortened Russian service rifle is outfitted with an extended Drum magazine, giving it a huge capacity for ammunition."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Obrez Mace",
        "slot_id" => 2,
        "damage" => 133,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 133,
        "effective_range" => 314,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 54,
        "heavy_melee_dmg" => 90,
        "cost" => 310,
        "summary" => "This shortened Russian service rifle has been additionally modified with a weighted mace stock, making it a competent melee weapon."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Bayonet",
        "slot_id" => 3,
        "damage" => 136,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 77,
        "effective_range" => 320,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 168,
        "cost" => 507,
        "summary" => "Modern Imperial Russian bolt-action service rifle with an internal magazine. Its attached spike bayonet turns it into a frightening melee weapon."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Sniper",
        "slot_id" => 2,
        "damage" => 136,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 69,
        "effective_range" => 320,
        "reload_time" => 5.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 550,
        "summary" => "Modern Imperial Russian bolt-action service rifle. The attached long scope provides accuracy at range, but prevents the use of stripper clips for fast reloading."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Avtomat",
        "slot_id" => 3,
        "damage" => 136,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 615,
        "sway" => 133,
        "effective_range" => 320,
        "reload_time" => 11.4,
        "cycle_time" => 0.1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 1250,
        "summary" => "The Mosin-Nagant M1891 Avtomat is a heavily modified fully automatic Russian service rifle with an increased internal magazine."
    ],
    [
        "variant_name" => "Romero 77 Talon",
        "slot_id" => 3,
        "damage" => 218,
        "variant_img" => "",
        "ammo_reserve" => 13,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 3.4,
        "cycle_time" => 4.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 330,
        "cost" => 84,
        "summary" => "Classic break-action shotgun with a long barrel. Decent power, range, and attached blades for close combat make this a very flexible weapon to bring along."
    ],
    [
        "variant_name" => "Winfield 1893 Slate Riposte",
        "slot_id" => 3,
        "damage" => 203,
        "variant_img" => "",
        "ammo_reserve" => 12,
        "bullet_speed" => 425,
        "sway" => 84,
        "effective_range" => 14,
        "reload_time" => 9.6,
        "cycle_time" => 1,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 359,
        "summary" => "Exposed hammer, pump-action Winfield Model 93 shotgun with bayonet affixed for mastery of close quarter combat."
    ],
    [
        "variant_name" => "Caldwell Rival 78 Trauma",
        "slot_id" => 3,
        "damage" => 190,
        "variant_img" => "",
        "ammo_reserve" => 8,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 4.7,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 216,
        "cost" => 170,
        "summary" => "Sturdy, break-action, side-by-side shotgun with a medium-length barrel that can destroy all but the toughest targets at close range. Provided with a mace at the end of the handle."
    ],
    [
        "variant_name" => "Caldwell Rival 78 Handcannon",

        "slot_id" => 3,
        "damage" => 105,
        "variant_img" => "",
        "ammo_reserve" => 8,
        "bullet_speed" => 350,
        "sway" => 133,
        "effective_range" => 13,
        "reload_time" => 4.7,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 125,
        "summary" => "Sawn-off break-action side-by-side shotgun. Its wider spread but shorter range make this a great backup weapon."
    ],
    [
        "variant_name" => "Specter 1882 Bayonet",
        "slot_id" => 3,
        "damage" => 190,
        "variant_img" => "",
        "ammo_reserve" => 14,
        "bullet_speed" => 400,
        "sway" => 84,
        "effective_range" => 14,
        "reload_time" => 14.8,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 211,
        "summary" => "Rapid firing, pump-action shotgun with medium barrel. Tooled up with sharp knife bayonet for close combat."
    ],
    [
        "variant_name" => "Specter 1882 Compact",
        "slot_id" => 2,
        "damage" => 113,
        "variant_img" => "",
        "ammo_reserve" => 12,
        "bullet_speed" => 350,
        "sway" => 87,
        "effective_range" => 10,
        "reload_time" => 11.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 164,
        "summary" => "Sawn-off, rapid firing, pump-action shotgun. While sacrificing accuracy and ammo capacity, the added foregrip keeps recoil under control in close quarter combat."
    ],
    [
        "variant_name" => "Springfield 1866 Compact",

        "slot_id" => 2,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 440,
        "sway" => 93,
        "effective_range" => 204,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 33,
        "summary" => "A shorter version of the classic breech-loading rifle with .50-70 caliber centerfire cartridges and a quick fire rate. Its sawn-off barrel and stock make the weapon hard to control, but a great backup."
    ],
    [
        "variant_name" => "Springfield 1866 Compact Deadeye",
        "slot_id" => 2,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 440,
        "sway" => 133,
        "effective_range" => 204,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 46,
        "summary" => 'Because of its compact size and mid-range scope, this rifle is considered the "pocket sniper" of the Springfield line.'
    ],
    [
        "variant_name" => "Springfield 1866 Compact Striker",
        "slot_id" => 2,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 440,
        "sway" => 93,
        "effective_range" => 204,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 52,
        "heavy_melee_dmg" => 105,
        "cost" => 47,
        "summary" => "A shorter, close-combat version of the classic breech-loading rifle with .50-70 caliber centerfire cartridges and a quick fire rate. The knife attached to its barrel can be used for both heavy and light melee attacks."
    ],
    [
        "variant_name" => "Springfield 1866 Marksman",

        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 490,
        "sway" => 77,
        "effective_range" => 212,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 73,
        "summary" => 'A shorter, scoped version of the classic breech-loading rifle with .50-70 caliber centerfire cartridges, quick fire rate, and stock. The scope is ideal to aid long-range shots.'
    ],
    [
        "variant_name" => "Springfield 1866 Bayonet",
        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 490,
        "sway" => 69,
        "effective_range" => 212,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 168,
        "cost" => 54,
        "summary" => "The original breech-loading Springfield 1866 with bayonet attachment, a powerful short-range addition."
    ],
    [
        "variant_name" => "Caldwell Conversion Uppercut Precision",
        "slot_id" => 2,
        "damage" => 123,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 410,
        "sway" => 87,
        "effective_range" => 115,
        "reload_time" => 18.3,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 54,
        "summary" => "Modified single-action revolver, with a stock to stabilize its powerful rifle cartridges."
    ],
];
