<?php
return [
    [
        "variant_name" => "Romero 77 Handcannon",
        "weapon_id" => 3,
        "slot_id" => 2,
        "damage" => 165,
        "variant_img" => "",
        "ammo_reserve" => 11,
        "bullet_speed" => 375,
        "sway" => 133,
        "effective_range" => 11,
        "reload_time" => 3.5,
        "cycle_time" => 4.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 26,
        "summary" => "The Romero 77 Handcannon is a sawn-off break-action single barrel shotgun. Easier to handle in tight spaces. Less accurate over long range."
    ],
    [
        "variant_name" => "Romero 77 Hatchet",
        "weapon_id" => 3,
        "slot_id" => 2,
        "damage" => 145,
        "variant_img" => "",
        "ammo_reserve" => 11,
        "bullet_speed" => 375,
        "sway" => 133,
        "effective_range" => 11,
        "reload_time" => 3.5,
        "cycle_time" => 4.4,
        "light_melee_dmg" => 90,
        "heavy_melee_dmg" => 150,
        "cost" => 62,
        "summary" => "The Romero 77 Hatchet is a sawn-off break-action single barrel shotgun. Easier to handle in tight spaces. Less accurate over long range. Hatchet causes rending damage."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Obrez",
        "weapon_id" => 14,
        "slot_id" => 2,
        "damage" => 133,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 133,
        "effective_range" => 314,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 26,
        "cost" => 290,
        "summary" => "Sawn-off variant of the Mosin-Nagant bolt-action rifle. Can be carried as a backup weapon that packs a punch, but without a stock its recoil is brutal."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Obrez Drum",
        "weapon_id" => 14,
        "slot_id" => 2,
        "damage" => 133,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 133,
        "effective_range" => 314,
        "reload_time" => 8,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 26,
        "cost" => 350,
        "summary" => "This shortened Russian service rifle is outfitted with an extended Drum magazine, giving it a huge capacity for ammunition."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Obrez Mace",
        "weapon_id" => 14,
        "slot_id" => 2,
        "damage" => 133,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 133,
        "effective_range" => 314,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 54,
        "heavy_melee_dmg" => 90,
        "cost" => 310,
        "summary" => "This shortened Russian service rifle has been additionally modified with a weighted mace stock, making it a competent melee weapon."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Bayonet",
        "weapon_id" => 14,
        "slot_id" => 3,
        "damage" => 136,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 77,
        "effective_range" => 320,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 168,
        "cost" => 507,
        "summary" => "Modern Imperial Russian bolt-action service rifle with an internal magazine. Its attached spike bayonet turns it into a frightening melee weapon."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Sniper",
        "weapon_id" => 14,
        "slot_id" => 2,
        "damage" => 136,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 550,
        "sway" => 69,
        "effective_range" => 320,
        "reload_time" => 5.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 550,
        "summary" => "Modern Imperial Russian bolt-action service rifle. The attached long scope provides accuracy at range, but prevents the use of stripper clips for fast reloading."
    ],
    [
        "variant_name" => "Mosin-Nagant M1891 Avtomat",
        "weapon_id" => 14,
        "slot_id" => 3,
        "damage" => 136,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 615,
        "sway" => 133,
        "effective_range" => 320,
        "reload_time" => 11.4,
        "cycle_time" => 0.1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 1250,
        "summary" => "The Mosin-Nagant M1891 Avtomat is a heavily modified fully automatic Russian service rifle with an increased internal magazine."
    ],
    [
        "variant_name" => "Romero 77 Talon",
        "weapon_id" => 3,
        "slot_id" => 3,
        "damage" => 218,
        "variant_img" => "",
        "ammo_reserve" => 13,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 3.4,
        "cycle_time" => 4.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 330,
        "cost" => 84,
        "summary" => "Classic break-action shotgun with a long barrel. Decent power, range, and attached blades for close combat make this a very flexible weapon to bring along."
    ],
    [
        "variant_name" => "Winfield 1893 Slate Riposte",
        "weapon_id" => 6,
        "slot_id" => 3,
        "damage" => 203,
        "variant_img" => "",
        "ammo_reserve" => 12,
        "bullet_speed" => 425,
        "sway" => 84,
        "effective_range" => 14,
        "reload_time" => 9.6,
        "cycle_time" => 1,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 359,
        "summary" => "Exposed hammer, pump-action Winfield Model 93 shotgun with bayonet affixed for mastery of close quarter combat."
    ],
    [
        "variant_name" => "Caldwell Rival 78 Trauma",
        "weapon_id" => 8,
        "slot_id" => 3,
        "damage" => 190,
        "variant_img" => "",
        "ammo_reserve" => 8,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 4.7,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 216,
        "cost" => 170,
        "summary" => "Sturdy, break-action, side-by-side shotgun with a medium-length barrel that can destroy all but the toughest targets at close range. Provided with a mace at the end of the handle."
    ],
    [
        "variant_name" => "Caldwell Rival 78 Handcannon",
        "weapon_id" => 8,
        "slot_id" => 3,
        "damage" => 105,
        "variant_img" => "",
        "ammo_reserve" => 8,
        "bullet_speed" => 350,
        "sway" => 133,
        "effective_range" => 13,
        "reload_time" => 4.7,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 125,
        "summary" => "Sawn-off break-action side-by-side shotgun. Its wider spread but shorter range make this a great backup weapon."
    ],
    [
        "variant_name" => "Specter 1882 Bayonet",
        "weapon_id" => 5,
        "slot_id" => 3,
        "damage" => 190,
        "variant_img" => "",
        "ammo_reserve" => 14,
        "bullet_speed" => 400,
        "sway" => 84,
        "effective_range" => 14,
        "reload_time" => 14.8,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 211,
        "summary" => "Rapid firing, pump-action shotgun with medium barrel. Tooled up with sharp knife bayonet for close combat."
    ],
    [
        "variant_name" => "Specter 1882 Compact",
        "weapon_id" => 5,
        "slot_id" => 2,
        "damage" => 113,
        "variant_img" => "",
        "ammo_reserve" => 12,
        "bullet_speed" => 350,
        "sway" => 87,
        "effective_range" => 10,
        "reload_time" => 11.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 164,
        "summary" => "Sawn-off, rapid firing, pump-action shotgun. While sacrificing accuracy and ammo capacity, the added foregrip keeps recoil under control in close quarter combat."
    ],
    [
        "variant_name" => "Springfield 1866 Compact",
        "weapon_id" => 16,
        "slot_id" => 2,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 440,
        "sway" => 93,
        "effective_range" => 204,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 33,
        "summary" => "A shorter version of the classic breech-loading rifle with .50-70 caliber centerfire cartridges and a quick fire rate. Its sawn-off barrel and stock make the weapon hard to control, but a great backup."
    ],
    [
        "variant_name" => "Springfield 1866 Compact Deadeye",
        "weapon_id" => 16,
        "slot_id" => 2,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 440,
        "sway" => 133,
        "effective_range" => 204,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 46,
        "summary" => 'Because of its compact size and mid-range scope, this rifle is considered the "pocket sniper" of the Springfield line.'
    ],
    [
        "variant_name" => "Springfield 1866 Compact Striker",
        "weapon_id" => 16,
        "slot_id" => 2,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 440,
        "sway" => 93,
        "effective_range" => 204,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 52,
        "heavy_melee_dmg" => 105,
        "cost" => 47,
        "summary" => "A shorter, close-combat version of the classic breech-loading rifle with .50-70 caliber centerfire cartridges and a quick fire rate. The knife attached to its barrel can be used for both heavy and light melee attacks."
    ],
    [
        "variant_name" => "Springfield 1866 Marksman",
        "weapon_id" => 16,
        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 490,
        "sway" => 77,
        "effective_range" => 212,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 73,
        "summary" => 'A shorter, scoped version of the classic breech-loading rifle with .50-70 caliber centerfire cartridges, quick fire rate, and stock. The scope is ideal to aid long-range shots.'
    ],
    [
        "variant_name" => "Springfield 1866 Bayonet",
        "weapon_id" => 16,
        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 25,
        "bullet_speed" => 490,
        "sway" => 69,
        "effective_range" => 212,
        "reload_time" => 3,
        "cycle_time" => 3.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 168,
        "cost" => 54,
        "summary" => "The original breech-loading Springfield 1866 with bayonet attachment, a powerful short-range addition."
    ],
    [
        "variant_name" => "Caldwell Conversion Uppercut Precision",
        "weapon_id" => 31,
        "slot_id" => 2,
        "damage" => 123,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 410,
        "sway" => 87,
        "effective_range" => 115,
        "reload_time" => 18.3,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 425,
        "summary" => "Modified single-action revolver, with a stock to stabilize its powerful rifle cartridges."
    ],
    [
        "variant_name" => "Caldwell Conversion Uppercut Precision Deadeye",
        "weapon_id" => 31,
        "slot_id" => 2,
        "damage" => 123,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 410,
        "sway" => 87,
        "effective_range" => 115,
        "reload_time" => 18.3,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 453,
        "summary" => "Modified single-action revolver, with a stock to stabilize its powerful rifle cartridges and a Deadeye scope to complement its performance at midrange."
    ],
    [
        "variant_name" => "Winfield M1876 Centennial Shorty Silencer",
        "weapon_id" => 21,
        "slot_id" => 2,
        "damage" => 120,
        "variant_img" => "",
        "ammo_reserve" => 17,
        "bullet_speed" => 390,
        "sway" => 133,
        "effective_range" => 145,
        "reload_time" => 10.9,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 137,
        "summary" => "This particular version of the Winfield M1887 Centennial features a suppressor to mask the volume of the powerful repeating rifle."
    ],
    [
        "variant_name" => "Winfield M1876 Centennial Shorty",
        "weapon_id" => 21,
        "slot_id" => 2,
        "damage" => 120,
        "variant_img" => "",
        "ammo_reserve" => 17,
        "bullet_speed" => 540,
        "sway" => 133,
        "effective_range" => 170,
        "reload_time" => 10.9,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 137,
        "summary" => "This particular version of the Winfield M1887 Centennial is shortened for more dynamic shooting ability without sacrificing magazine capacity or firing power."
    ],
    [
        "variant_name" => "Drilling Handcannon",
        "weapon_id" => 22,
        "slot_id" => 2,
        "damage" => 120,
        "variant_img" => "",
        "ammo_reserve" => 22,
        "bullet_speed" => 424,
        "sway" => 108,
        "effective_range" => 170,
        "reload_time" => 4.8,
        "cycle_time" => 0.6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 430,
        "summary" => "Two medium rifle barrels combined with a shotgun underbarrel, all three shortened to make a smaller, more compact package."
    ],
    [
        "variant_name" => "Drilling Hatchet",
        "weapon_id" => 22,
        "slot_id" => 2,
        "damage" => 120,
        "variant_img" => "",
        "ammo_reserve" => 22,
        "bullet_speed" => 424,
        "sway" => 108,
        "effective_range" => 170,
        "reload_time" => 4.8,
        "cycle_time" => 0.6,
        "light_melee_dmg" => 90,
        "heavy_melee_dmg" => 150,
        "cost" => 450,
        "summary" => "Two medium rifle barrels combined with a shotgun underbarrel and an additional blade to create a powerful multipurpose weapon."
    ],
    [
        "variant_name" => "Frontier 73C Vandal",
        "weapon_id" => 25,
        "slot_id" => 2,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 34,
        "bullet_speed" => 370,
        "sway" => 108,
        "effective_range" => 141,
        "reload_time" => 9.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 35,
        "summary" => "A shortened Winfield M1873C, fires compact bullets at rapid speed."
    ],
    [
        "variant_name" => "Frontier 73C Vandal Striker",
        "weapon_id" => 25,
        "slot_id" => 2,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 34,
        "bullet_speed" => 370,
        "sway" => 108,
        "effective_range" => 141,
        "reload_time" => 9.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 52,
        "heavy_melee_dmg" => 105,
        "cost" => 39,
        "summary" => "A shortened Winfield M1873C, fires compact bullets at rapid speed and with a blade for melee purposes."
    ],
    [
        "variant_name" => "Frontier 73C Vandal Deadeye",
        "weapon_id" => 25,
        "slot_id" => 2,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 34,
        "bullet_speed" => 370,
        "sway" => 108,
        "effective_range" => 141,
        "reload_time" => 9.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 45,
        "summary" => "A shortened Winfield M1873C, fires compact bullets at rapid speed. Equipped with a scope for mid-range fights."
    ],
    [
        "variant_name" => "Frontier 73C Silencer",
        "weapon_id" => 25,
        "slot_id" => 3,
        "damage" => 110,
        "variant_img" => "",
        "ammo_reserve" => 35,
        "bullet_speed" => 250,
        "sway" => 87,
        "effective_range" => 136,
        "reload_time" => 10.1,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 55,
        "summary" => "Lightened repeating rifle with demi-size internal magazine, capable of firing compact bullets at rapid speed. Comes with a silencer."
    ],
    [
        "variant_name" => "Frontier 73C Marksman",
        "weapon_id" => 25,
        "slot_id" => 3,
        "damage" => 110,
        "variant_img" => "",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 87,
        "effective_range" => 151,
        "reload_time" => 10.3,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 56,
        "summary" => "Lightened repeating rifle with demi-size internal magazine, capable of firing compact bullets at rapid speed. Mounted with a medium scope for enhanced precision."
    ],
    [
        "variant_name" => "LeMat Mark II Carbine",
        "weapon_id" => 28,
        "slot_id" => 3,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 27,
        "bullet_speed" => 360,
        "sway" => 77,
        "effective_range" => 141,
        "reload_time" => 18.7,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 115,
        "summary" => "The LeMat Mark II's unique design that featured an extra shotgun barrel made it very effective in close quarters. This model transforms it into a rifle with a stock and extended barrel, improving its overall handling and power."
    ],
    [
        "variant_name" => "LeMat Mark II Carbine Marksman",
        "weapon_id" => 28,
        "slot_id" => 3,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 27,
        "bullet_speed" => 360,
        "sway" => 87,
        "effective_range" => 141,
        "reload_time" => 18.7,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 115,
        "summary" => "The LeMat Mark II's unique design that featured an extra shotgun barrel made it very effective in close quarters. This model transforms it into a rifle with a stock and extended barrel, improving its overall handling and power. Mounted with a medium scope for enhanced precision."
    ],
    [
        "variant_name" => "Nagant M1895 Officer Carbine",
        "weapon_id" => 35,
        "slot_id" => 3,
        "damage" => 104,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 360,
        "sway" => 77,
        "effective_range" => 141,
        "reload_time" => 13.4,
        "cycle_time" => 0.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 183,
        "summary" => "Modern, Imperial Russian, double-action revolver variant. This model is heavily modified with a longer barrel and a stock, effectively turning it into a small rapid-fire rifle."
    ],
    [
        "variant_name" => "Nagant M1895 Officer Carbine Deadeye",
        "weapon_id" => 35,
        "slot_id" => 3,
        "damage" => 104,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 360,
        "sway" => 77,
        "effective_range" => 141,
        "reload_time" => 13.4,
        "cycle_time" => 0.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 183,
        "summary" => "Modern, Imperial Russian, double-action revolver variant. This model is heavily modified with a longer barrel and a stock, effectively turning it into a small rapid-fire rifle. Mounted with a small scope for enhanced precision."
    ],
    [
        "variant_name" => "Nagant M1895 Officer Brawler",
        "weapon_id" => 35,
        "slot_id" => 1,
        "damage" => 91,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 360,
        "sway" => 128,
        "effective_range" => 74,
        "reload_time" => 12.8,
        "cycle_time" => 0.5,
        "light_melee_dmg" => 31,
        "heavy_melee_dmg" => 72,
        "cost" => 110,
        "summary" => "Modern, Imperial Russian, double-action revolver variant. The weight of this piece is put to good use with an integrated knuckle duster."
    ],
    [
        "variant_name" => "Winfield M1873 Talon",
        "weapon_id" => 24,
        "slot_id" => 3,
        "damage" => 110,
        "variant_img" => "",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 151,
        "reload_time" => 16.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 330,
        "cost" => 100,
        "summary" => "Modified iconic repeating rifle with very large internal magazine. The stock is mounted with blades for melee combat."
    ],
    [
        "variant_name" => "Winfield M1873 Swift",
        "weapon_id" => 24,
        "slot_id" => 3,
        "damage" => 110,
        "variant_img" => "",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 151,
        "reload_time" => 8.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 128,
        "summary" => "Modified iconic repeating rifle with very large internal magazine. Reloading is quickened with a speed loader mechanism."
    ],
    [
        "variant_name" => "Winfield M1873 Aperture",
        "weapon_id" => 24,
        "slot_id" => 3,
        "damage" => 110,
        "variant_img" => "",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 69,
        "effective_range" => 151,
        "reload_time" => 16.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 80,
        "summary" => "Modified iconic repeating rifle with very large internal magazine. The Aperture sight makes it easier to aim more precisely at medium ranges."
    ],
    [
        "variant_name" => "Caldwell Marathon Swift",
        "weapon_id" => 23,
        "slot_id" => 3,
        "damage" => 113,
        "variant_img" => "",
        "ammo_reserve" => 39,
        "bullet_speed" => 430,
        "sway" => 69,
        "effective_range" => 160,
        "reload_time" => 10,
        "cycle_time" => 1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 95,
        "summary" => "Fast-firing pump-action rifle that performs best at mid-range. Reloading is quickened with a speed loader mechanism."
    ],
    [
        "variant_name" => "Winfield M1876 Centennial Trauma",
        "weapon_id" => 21,
        "slot_id" => 3,
        "damage" => 123,
        "variant_img" => "",
        "ammo_reserve" => 31,
        "bullet_speed" => 600,
        "sway" => 77,
        "effective_range" => 180,
        "reload_time" => 15.5,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 216,
        "cost" => 200,
        "summary" => "This particular version of the Winfield M1876 Centennial features a reinforced stock that delivers a hit as heavy and deadly as a sledgehammer, which makes the rifle viable in melee combat."
    ],
    [
        "variant_name" => "Winfield M1876 Centennial Sniper",
        "weapon_id" => 21,
        "slot_id" => 3,
        "damage" => 123,
        "variant_img" => "",
        "ammo_reserve" => 31,
        "bullet_speed" => 600,
        "sway" => 77,
        "effective_range" => 180,
        "reload_time" => 15.5,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 216,
        "cost" => 229,
        "summary" => "Powerful repeating rifle with good stopping power and an attached scope, highly effective at long range. The magazine holds nine rounds."
    ],
    [
        "variant_name" => "Vetterli 71 Karabiner Cyclone",
        "weapon_id" => 17,
        "slot_id" => 3,
        "damage" => 124,
        "variant_img" => "",
        "ammo_reserve" => 24,
        "bullet_speed" => 410,
        "sway" => 77,
        "effective_range" => 185,
        "reload_time" => 8.4,
        "cycle_time" => 0.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 208,
        "summary" => "Swiss military, semi-automatic carbine with a reduced internal magazine to compensate for its self-loading mechanism. Powerful at medium distances."
    ],
    [
        "variant_name" => "Vetterli 71 Karabiner Deadeye",
        "weapon_id" => 17,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 27,
        "bullet_speed" => 410,
        "sway" => 77,
        "effective_range" => 204,
        "reload_time" => 12.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 130,
        "summary" => "Swiss Military, bolt-action carbine with internal magazine. A short scope makes this weapon very effective at longer ranges."
    ],
    [
        "variant_name" => "Vetterli 71 Karabiner Marksman",
        "weapon_id" => 17,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 27,
        "bullet_speed" => 410,
        "sway" => 77,
        "effective_range" => 204,
        "reload_time" => 12.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 135,
        "summary" => "Swiss Military, bolt-action carbine with internal magazine. A medium scope makes this weapon very effective at longer ranges."
    ],
    [
        "variant_name" => "Vetterli 71 Karabiner Silencer",
        "weapon_id" => 17,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 27,
        "bullet_speed" => 410,
        "sway" => 84,
        "effective_range" => 204,
        "reload_time" => 12.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 115,
        "summary" => "Swiss Military, bolt-action carbine with internal magazine. Equipped with a suppressor."
    ],
    [
        "variant_name" => "Vetterli 71 Karabiner Bayonet",
        "weapon_id" => 17,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 27,
        "bullet_speed" => 410,
        "sway" => 84,
        "effective_range" => 204,
        "reload_time" => 12.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 168,
        "cost" => 115,
        "summary" => "Swiss Military, bolt-action carbine with internal magazine. The attached bayonet makes this a great choice for close combat."
    ],
    [
        "variant_name" => "Sparks LRR Silencer",
        "weapon_id" => 11,
        "slot_id" => 3,
        "damage" => 149,
        "variant_img" => "",
        "ammo_reserve" => 17,
        "bullet_speed" => 300,
        "sway" => 87,
        "effective_range" => 169,
        "reload_time" => 4,
        "cycle_time" => 4.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 150,
        "summary" => "Renowned, large-bore single shot rifle modified with a silencer."
    ],
    [
        "variant_name" => "Sparks LRR Sniper",
        "weapon_id" => 11,
        "slot_id" => 3,
        "damage" => 149,
        "variant_img" => "",
        "ammo_reserve" => 17,
        "bullet_speed" => 533,
        "sway" => 87,
        "effective_range" => 347,
        "reload_time" => 4,
        "cycle_time" => 4.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 199,
        "summary" => "Renowned, large-bore, single-shot rifle mounted with a long scope for even greater effectiveness over distance."
    ],
    [
        "variant_name" => "Sparks LRR Pistol",
        "weapon_id" => 11,
        "slot_id" => 1,
        "damage" => 149,
        "variant_img" => "",
        "ammo_reserve" => 17,
        "bullet_speed" => 453,
        "sway" => 128,
        "effective_range" => 150,
        "reload_time" => 5,
        "cycle_time" => 5.9,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 155,
        "summary" => "A Sparks LRR cut down to be a small handgun, the Sparks Pistol delivers equally powerful shots over short to medium ranges. Though small and easy to carry, it loses its power drastically over longer distances, and has a stronger recoil because of the missing stock."
    ],
    [
        "variant_name" => "Martini-Henry IC1 Deadeye",
        "weapon_id" => 12,
        "slot_id" => 3,
        "damage" => 143,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 400,
        "sway" => 87,
        "effective_range" => 334,
        "reload_time" => 2.5,
        "cycle_time" => 3.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 140,
        "summary" => "This single-shot breech-loading rifle is furnished with a Deadeye scope that complements its competent range and power."
    ],
    [
        "variant_name" => "Martini-Henry IC1 Marksman",
        "weapon_id" => 12,
        "slot_id" => 3,
        "damage" => 143,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 400,
        "sway" => 87,
        "effective_range" => 334,
        "reload_time" => 2.5,
        "cycle_time" => 3.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 157,
        "summary" => "This single-shot breech-loading rifle is furnished with a Marksman scope that complements its competent range and power."
    ],
    [
        "variant_name" => "Martini-Henry IC1 Riposte",
        "weapon_id" => 12,
        "slot_id" => 3,
        "damage" => 143,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 400,
        "sway" => 84,
        "effective_range" => 334,
        "reload_time" => 2.5,
        "cycle_time" => 3.5,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 137,
        "summary" => "This single-shot breech-loading rifle is equipped with a long-bladed saber bayonet that is deadly in close quarters."
    ],
    [
        "variant_name" => "Lebel 1886 Marksman",
        "weapon_id" => 15,
        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 630,
        "sway" => 69,
        "effective_range" => 311,
        "reload_time" => 18.7,
        "cycle_time" => 1.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 607,
        "summary" => "A version of the Lebel 1886 bolt-action rifle with a mounted medium scope that ensures higher accuracy at a distance."
    ],
    [
        "variant_name" => "Lebel 1886 Aperture",
        "weapon_id" => 15,
        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 630,
        "sway" => 69,
        "effective_range" => 311,
        "reload_time" => 18.7,
        "cycle_time" => 1.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 425,
        "summary" => "The groundbreaking Lebel 1886 bolt-action rifle with a toggle-able aperture sight which ensures higher precision at medium ranges."
    ],
    [
        "variant_name" => "Lebel 1886 Talon",
        "weapon_id" => 15,
        "slot_id" => 3,
        "damage" => 132,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 630,
        "sway" => 69,
        "effective_range" => 311,
        "reload_time" => 18.7,
        "cycle_time" => 1.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 330,
        "cost" => 422,
        "summary" => "This variant of the Lebel 1886 bolt-action rifle doubles as a deadly melee weapon thanks to the axe blade attached to the buttstock."
    ],
    [
        "variant_name" => "Berthier Mle 1892 Riposte",
        "weapon_id" => 18,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 590,
        "sway" => 84,
        "effective_range" => 305,
        "reload_time" => 2.7,
        "cycle_time" => 1.7,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 370,
        "summary" => "The light Berthier Mle 1892 is a bolt-action mousqueton that doesn't lose power for the sake of its convenience. An affixed bayonet makes this deadly in close combat."
    ],
    [
        "variant_name" => "Berthier Mle 1892 Deadeye",
        "weapon_id" => 18,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 590,
        "sway" => 77,
        "effective_range" => 305,
        "reload_time" => 2.7,
        "cycle_time" => 1.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 388,
        "summary" => "The light Berthier Mle 1892 is a bolt-action mousqueton that doesn't lose power for the sake of its convenience. A Deadeye scope complements its performance at midrange."
    ],
    [
        "variant_name" => "Berthier Mle 1892 Marksman",
        "weapon_id" => 18,
        "slot_id" => 3,
        "damage" => 130,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 590,
        "sway" => 77,
        "effective_range" => 305,
        "reload_time" => 2.7,
        "cycle_time" => 1.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 580,
        "summary" => "The Berthier Mle 1892 is a bolt-action mousqueton that doesn't lose power for the sake of its convenience, A Marksman scope gives the rifle an advantage at distance."
    ],
    [
        "variant_name" => "Mako 1895 Carabine Aperture",
        "weapon_id" => 19,
        "slot_id" => 3,
        "damage" => 128,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 540,
        "sway" => 69,
        "effective_range" => 302,
        "reload_time" => 13,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 385,
        "summary" => "Long range, lever-action rifle that delivers a powerful punch with long ammo. Its toggle-able Aperture sight ensures higher precision at medium ranges."
    ],
    [
        "variant_name" => "Mako 1895 Carabine Claw",
        "weapon_id" => 19,
        "slot_id" => 3,
        "damage" => 128,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 540,
        "sway" => 69,
        "effective_range" => 302,
        "reload_time" => 13,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 120,
        "heavy_melee_dmg" => 54,
        "cost" => 375,
        "summary" => "Long range, lever-action rifle that delivers a powerful punch with long ammo. A robust hooked blade is affixed to make the gun a melee and ranged weapon."
    ],
    [
        "variant_name" => "Springfield M1892 Krag Bayonet",
        "weapon_id" => 20,
        "slot_id" => 3,
        "damage" => 126,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 610,
        "sway" => 77,
        "effective_range" => 291,
        "reload_time" => 11.1,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 168,
        "cost" => 391,
        "summary" => "The easy-reloading Springfield M1892 Krag bolt-action rifle, with bayonet attached for close quarters combat."
    ],
    [
        "variant_name" => "Springfield M1892 Krag Sniper",
        "weapon_id" => 20,
        "slot_id" => 3,
        "damage" => 126,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 610,
        "sway" => 69,
        "effective_range" => 291,
        "reload_time" => 11.1,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 579,
        "summary" => "The original repeating, bolt-action Springfield M1892 Krag with a sniper scope attached to it, making the rifle even more efficient over longer ranges."
    ],
    [
        "variant_name" => "Scottfield Model 3 Precision",
        "weapon_id" => 30,
        "slot_id" => 2,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 280,
        "sway" => 87,
        "effective_range" => 85,
        "reload_time" => 9,
        "cycle_time" => 1.0,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 85,
        "summary" => "The buttstock on this Scottfield Model 3 allows for a more stable shot with steady aim and less kickback."
    ],
    [
        "variant_name" => "Scottfield Model 3 Brawler",
        "weapon_id" => 30,
        "slot_id" => 1,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 280,
        "sway" => 128,
        "effective_range" => 85,
        "reload_time" => 9,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 31,
        "heavy_melee_dmg" => 72,
        "cost" => 92,
        "summary" => "This snub barrel Scottfield Model 3 not only has the quick reload Hunters have come to know, but an added pair of dusters for close combat at the cost of accuracy."
    ],
    [
        "variant_name" => "Scottfield Model 3 Spitfire",
        "weapon_id" => 30,
        "slot_id" => 1,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 280,
        "sway" => 115,
        "effective_range" => 85,
        "reload_time" => 9,
        "cycle_time" => 0.8,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 108,
        "summary" => "Its shortened barrel makes the Scottfield Model 3 Spitfire a perfect choice for situations that require discretion, and its modified finger rest provides higher rate of fire in exchange for accuracy."
    ],
    [
        "variant_name" => "Scottfield Model 3 Swift",
        "weapon_id" => 30,
        "slot_id" => 1,
        "damage" => 107,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 280,
        "sway" => 128,
        "effective_range" => 85,
        "reload_time" => 4.3,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 95,
        "summary" => "The Scottfield Model 3 Swift allows for an even quicker reload with the help of a device that lets the wielder load six cartridges together into the empty cylinder. However, any unspent ammunition is lost in the process of reloading."
    ],
    [
        "variant_name" => "Winfield 1887 Terminus Handcannon",
        "weapon_id" => 9,
        "slot_id" => 2,
        "damage" => 105,
        "variant_img" => "",
        "ammo_reserve" => 12,
        "bullet_speed" => 350,
        "sway" => 133,
        "effective_range" => 10,
        "reload_time" => 10.6,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 218,
        "summary" => "Seminal sawn-off lever-action repeating shotgun. Shortened to reduce size and increase lethality at close range, this packs high power for its size. Chambers 4+2 shells."
    ],
    [
        "variant_name" => "Dolch 96 Precision",
        "weapon_id" => 32,
        "slot_id" => 2,
        "damage" => 97,
        "variant_img" => "",
        "ammo_reserve" => 20,
        "bullet_speed" => 440,
        "sway" => 87,
        "effective_range" => 78,
        "reload_time" => 6,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 730,
        "summary" => "Powerful, German, prototype, semi-automatic pistol. The wooden holster is attached as a makeshift buttstock for accurate fire over distance."
    ],
    [
        "variant_name" => "Dolch 96 Claw",
        "weapon_id" => 32,
        "slot_id" => 1,
        "damage" => 97,
        "variant_img" => "",
        "ammo_reserve" => 20,
        "bullet_speed" => 440,
        "sway" => 87,
        "effective_range" => 78,
        "reload_time" => 6,
        "cycle_time" => 0.4,
        "light_melee_dmg" => 52,
        "heavy_melee_dmg" => 105,
        "cost" => 710,
        "summary" => "The German, prototype, semi-automatic pistol, with a robust hooked blade affixed for hand-to-hand combat. This weapon can dual wielded."
    ],
    [
        "variant_name" => "Dolch 96 Deadeye",
        "weapon_id" => 32,
        "slot_id" => 1,
        "damage" => 97,
        "variant_img" => "",
        "ammo_reserve" => 20,
        "bullet_speed" => 440,
        "sway" => 106,
        "effective_range" => 78,
        "reload_time" => 21.7,
        "cycle_time" => 0.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 725,
        "summary" => "The German, prototype, semi-automatic pistol with a short scope to fully utilize the weapon's power at midrange. Cannot use a stripper clip to be reloaded."
    ],
    [
        "variant_name" => "Nagant M1895 Deadeye",
        "weapon_id" => 34,
        "slot_id" => 2,
        "damage" => 91,
        "variant_img" => "",
        "ammo_reserve" => 28,
        "bullet_speed" => 330,
        "sway" => 87,
        "effective_range" => 74,
        "reload_time" => 13.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 42,
        "summary" => "Modified, Russian, single-action, seven-round revolver. Telescopic sight and rifle stock make it an unconventional sniper."
    ],
    [
        "variant_name" => "Nagant M1895 Precision",
        "weapon_id" => 34,
        "slot_id" => 2,
        "damage" => 91,
        "variant_img" => "",
        "ammo_reserve" => 28,
        "bullet_speed" => 330,
        "sway" => 87,
        "effective_range" => 74,
        "reload_time" => 13.4,
        "cycle_time" => 1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 29,
        "summary" => "Modern, Imperial Russian, single-action revolver. The attached stock improves accuracy and handling, making it easier to operate the hammer between shots at a faster rate."
    ],
    [
        "variant_name" => "Nagant M1895 Silencer",
        "weapon_id" => 34,
        "slot_id" => 1,
        "damage" => 91,
        "variant_img" => "",
        "ammo_reserve" => 28,
        "bullet_speed" => 250,
        "sway" => 128,
        "effective_range" => 57,
        "reload_time" => 12.5,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 93,
        "summary" => "Modern, Imperial Russian, single-action revolver. Unique among revolvers of this era. The cylinder gas seal suppresses the sound of its fire."
    ],
    [
        "variant_name" => "Bornheim No. 3 Match",
        "weapon_id" => 36,
        "slot_id" => 2,
        "damage" => 80,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 400,
        "sway" => 87,
        "effective_range" => 67,
        "reload_time" => 7.6,
        "cycle_time" => 0.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 180,
        "summary" => "This early German semi-automatic pistol can reliably put down targets at a distance, making use of its low recoil and fast reload."
    ],
    [
        "variant_name" => "Bornheim No. 3 Silencer",
        "weapon_id" => 36,
        "slot_id" => 1,
        "damage" => 74,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 300,
        "sway" => 128,
        "effective_range" => 48,
        "reload_time" => 7.4,
        "cycle_time" => 0.2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 174,
        "summary" => "This early German semi-automatic pistol can release a hail of accurate fire by virtue of its low recoil. An attached silencer masks the rapid gunfire."
    ],
    [
        "variant_name" => "Bornheim No. 3 Extended",
        "weapon_id" => 36,
        "slot_id" => 1,
        "damage" => 74,
        "variant_img" => "",
        "ammo_reserve" => 21,
        "bullet_speed" => 380,
        "sway" => 128,
        "effective_range" => 48,
        "reload_time" => 9.6,
        "cycle_time" => 0.2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 174,
        "summary" => "This early German semi-automatic pistol can release a hail of accurate fire by virtue of its low recoil. Modified to increase capacity by removing the option to reload via magazine."
    ],
    [
        "variant_name" => "Hand Crossbow",
        "weapon_id" => 2,
        "slot_id" => 1,
        "damage" => 195,
        "variant_img" => "",
        "ammo_reserve" => 17,
        "bullet_speed" => 100,
        "sway" => 82,
        "effective_range" => 12,
        "reload_time" => 4.3,
        "cycle_time" => 4.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 27,
        "cost" => 30,
        "summary" => "Imaginative hand crossbow that fires compact bolts. Excels in situations when discretion is required above all. Bolts can be retrieved and re-used."
    ],
    [
        "variant_name" => "Caldwell Conversion Uppercut",
        "weapon_id" => 31,
        "slot_id" => 1,
        "damage" => 123,
        "variant_img" => "",
        "ammo_reserve" => 15,
        "bullet_speed" => 410,
        "sway" => 128,
        "effective_range" => 115,
        "reload_time" => 16,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 414,
        "summary" => "Modified single-action revolver that fires more powerful rifle cartridges, but kicks like a mule."
    ],
    [
        "variant_name" => "Caldwell Conversion Chain Pistol",
        "weapon_id" => 31,
        "slot_id" => 1,
        "damage" => 104,
        "variant_img" => "",
        "ammo_reserve" => 35,
        "bullet_speed" => 300,
        "sway" => 128,
        "effective_range" => 115,
        "reload_time" => 28.7,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 84,
        "summary" => "Modified single-action revolver that chambers 17 rounds in a revolving chain for sustained fire."
    ],
    [
        "variant_name" => "Caldwell Pax Trueshot",
        "weapon_id" => 29,
        "slot_id" => 1,
        "damage" => 114,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 410,
        "sway" => 128,
        "effective_range" => 89,
        "reload_time" => 11.2,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 141,
        "summary" => "The iconic single-action six round revolver with an extended barrel that increases muzzle velocity. Robust, exceptionally powerful, and fairly accurate, it is the arm of the West's spreading law."
    ],
    [
        "variant_name" => "Caldwell Pax Claw",
        "weapon_id" => 29,
        "slot_id" => 1,
        "damage" => 110,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 330,
        "sway" => 128,
        "effective_range" => 87,
        "reload_time" => 11.2,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 52,
        "heavy_melee_dmg" => 105,
        "cost" => 105,
        "summary" => "Iconic single-action six round revolver. Robust, powerful, and accurate, a blade affixed to the grip gives this an edge up close."
    ],
    [
        "variant_name" => "Caldwell 92 New Army Swift",
        "weapon_id" => 29,
        "slot_id" => 1,
        "damage" => 97,
        "variant_img" => "",
        "ammo_reserve" => 18,
        "bullet_speed" => 230,
        "sway" => 128,
        "effective_range" => 80,
        "reload_time" => 5.6,
        "cycle_time" => 0.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 108,
        "summary" => "Faster reloading Caldwell 92 New Army pistol, thanks to a speed reloader. However, any unspent ammunition is lost in the process of reloading."
    ],
];
