<?php
return [
    [
        "weapon_name" => "Nitro Express Rifle",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 364,
        "weapon_img" => "weapons/nitro-express-rifle.jpg",
        "ammo_reserve" => 4,
        "bullet_speed" => 550,
        "sway" => 77,
        "effective_range" => 252,
        "reload_time" => 4.8,
        "cycle_time" => 0.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 1015,
        "summary" => "Powerful, side-by-side, big game hunting rifle that can bring down the largest targets at mid-range. Carries limited ammunition."
    ],
    [
        "weapon_name" => "Crossbow",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 247,
        "weapon_img" => "weapons/crossbow.jpeg",
        "ammo_reserve" => 10,
        "bullet_speed" => 150,
        "sway" => 77,
        "effective_range" => 47,
        "reload_time" => 5.3,
        "cycle_time" => 6.1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 73,
        "summary" => "Hand-crafted crossbow that fires powerful bolts. Well suited for covert missions and stealth takedowns, but has a long reload. Bolts can be retrieved and re-used."
    ],
    [
        "weapon_name" => "Romero 77",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 218,
        "weapon_img" => "weapons/romero77.jpeg",
        "ammo_reserve" => 7,
        "bullet_speed" => 450,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 3.4,
        "cycle_time" => 4.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 34,
        "summary" => "Classic break-action shotgun with a long barrel. Good range and power for a shotgun. Has to reload after every shot."
    ],
    [
        "weapon_name" => "Romero 77 Alamo",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 218,
        "weapon_img" => "weapons/romero77.jpeg",
        "ammo_reserve" => 7,
        "bullet_speed" => 450,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 18.2,
        "cycle_time" => 2.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 34,
        "summary" => "Classic break-action shotgun with a long barrel with more shell in the chamber. Good range and power for a shotgun. Has to reload after every shot."
    ],
    [
        "weapon_name" => "Specter 1882",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 210,
        "weapon_img" => "weapons/specter.jpg",
        "ammo_reserve" => 10,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 14.8,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 188,
        "summary" => "Revolutionary pump-action shotgun with long barrel, able to fire shells in rapid succession. Reloading the internal magazine takes time, due to its clunky, unrefined loading sequence."
    ],
    [
        "weapon_name" => "Winfield 1893 Slate",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 203,
        "weapon_img" => "weapons/slate.jpg",
        "ammo_reserve" => 11,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 9.6,
        "cycle_time" => 1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 333,
        "summary" => "An exposed hammer shotgun that replaces lever-action with pump-action, this Winfield Model 93 holds several 12-gauge rounds to cause devastating damage to opponents."
    ],
    [
        "weapon_name" => "Auto-5",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 194,
        "weapon_img" => "weapons/auto-5.jpg",
        "ammo_reserve" => 10,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 10.7,
        "cycle_time" => 0.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 600,
        "summary" => "Prototype long-barreled semi-automatic shotgun with internal four round magazine plus one in the chamber. High power and rate of fire, but strong recoil and short range."
    ],
    [
        "weapon_name" => "Caldwell Rival 78",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 190,
        "weapon_img" => "weapons/caldwellrival.jpg",
        "ammo_reserve" => 10,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 4.7,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 100,
        "summary" => "Sturdy, break-action, side-by-side shotgun with a medium-length barrel that can destroy all but the toughest targets at close range."
    ],
    [
        "weapon_name" => "Winfield 1887 Terminus",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 190,
        "weapon_img" => "weapons/terminus.jpg",
        "ammo_reserve" => 14,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 12.2,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 309,
        "summary" => "Seminal lever-action repeating shotgun. Boasting a balance between power and rate-of-fire, this became an icon of the era. Chamber 5+2 shells."
    ],
    [
        "weapon_name" => "Bomb Lance",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 150,
        "weapon_img" => "weapons/bomblance.jpg",
        "ammo_reserve" => 4,
        "bullet_speed" => 60,
        "sway" => 38,
        "effective_range" => 10,
        "reload_time" => 12.2,
        "cycle_time" => 7.8,
        "light_melee_dmg" => 180,
        "heavy_melee_dmg" => 360,
        "cost" => 199,
        "summary" => "Adapted for combat on land, this explosive harpoon can be fired short distances and deals tremendous damage on direct impact."
    ],
    [
        "weapon_name" => "Sparks LRR",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 149,
        "weapon_img" => "weapons/sparks.jpg",
        "ammo_reserve" => 16,
        "bullet_speed" => 533,
        "sway" => 77,
        "effective_range" => 347,
        "reload_time" => 4,
        "cycle_time" => 5.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 130,
        "summary" => "Renowned, large-bore, single-shot rifle with good sights. Can put down a bison across a prairie."
    ],
    [
        "weapon_name" => "Martini Henry IC1",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 143,
        "weapon_img" => "weapons/martini.jpg",
        "ammo_reserve" => 20,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 334,
        "reload_time" => 2.7,
        "cycle_time" => 4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 122,
        "summary" => "The workhorse rifle of the British Empire, the Martini-Henry IC1 is a single-shot breech-loading rifle that values simplicity and power."
    ],
    [
        "weapon_name" => "Martini Henry IC1 Ironside",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 143,
        "weapon_img" => "weapons/martiniironside.jpg",
        "ammo_reserve" => 20,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 334,
        "reload_time" => 14.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 184,
        "summary" => "This Martini-Henry IC1 features a mechanism carrying five extra cartridges in addition to the one in the rifle's chamber which allows the wielder to replace the spent cartridge in quick succession, transforming the weapon into a makeshift repeating rifle."
    ],
    [
        "weapon_name" => "Mosin-Nagant M1891",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 136,
        "weapon_img" => "weapons/mosin.jpg",
        "ammo_reserve" => 15,
        "bullet_speed" => 615,
        "sway" => 77,
        "effective_range" => 320,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 620,
        "summary" => "Modern Imperial Russian bolt-action service rifle with an internal magazine, firing powerful long cartridges. When fully emptied, can be reloaded fast with a five-round stripper clip."
    ],
    [
        "weapon_name" => "Lebel 1886",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 132,
        "weapon_img" => "weapons/lebel.jpg",
        "ammo_reserve" => 15,
        "bullet_speed" => 630,
        "sway" => 77,
        "effective_range" => 311,
        "reload_time" => 18.7,
        "cycle_time" => 1.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 397,
        "summary" => "Modern Imperial Russian bolt-action service rifle with an internal magazine, firing powerful long cartridges. When fully emptied, can be reloaded fast with a five-round stripper clip."
    ],
    [
        "weapon_name" => "Springfield 1866",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 132,
        "weapon_img" => "weapons/springfield.jpg",
        "ammo_reserve" => 25,
        "bullet_speed" => 490,
        "sway" => 77,
        "effective_range" => 212,
        "reload_time" => 3,
        "cycle_time" => 4.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 38,
        "summary" => "A breech-loading rifle with a .50-70 caliber centerfire cartridge, the Springfield 1866 is best known for its quick rate of fire."
    ],
    [
        "weapon_name" => "Vetterli 71 Karabiner",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 130,
        "weapon_img" => "weapons/vetterli.jpg",
        "ammo_reserve" => 26,
        "bullet_speed" => 410,
        "sway" => 77,
        "effective_range" => 204,
        "reload_time" => 12.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 105,
        "summary" => "Swiss military, bolt-action carbine with internal magazine. Powerful at medium distances. Reloading is inspired by the Winfield repeater rifle, making it easy to top up ammunition."
    ],
    [
        "weapon_name" => "Berthier Mle 1892",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 130,
        "weapon_img" => "weapons/berthier.jpg",
        "ammo_reserve" => 15,
        "bullet_speed" => 590,
        "sway" => 77,
        "effective_range" => 305,
        "reload_time" => 2.7,
        "cycle_time" => 1.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 330,
        "summary" => "The lighter alternative to the Lebel 1886, the Berthier Mle 1892 is a bolt-action mousqueton that doesn't lose power for the sake of its convenience."
    ],
    [
        "weapon_name" => "Mako 1895 Carbine",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 128,
        "weapon_img" => "weapons/mako.jpg",
        "ammo_reserve" => 14,
        "bullet_speed" => 540,
        "sway" => 77,
        "effective_range" => 302,
        "reload_time" => 13,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 360,
        "summary" => "Long range, lever-action rifle that delivers a powerful punch with long ammo. From a new manufacturer in competition with Winfield."
    ],
    [
        "weapon_name" => "Springfield M1892 Krag",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 126,
        "weapon_img" => "weapons/krag.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 610,
        "sway" => 77,
        "effective_range" => 291,
        "reload_time" => 11.1,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 345,
        "summary" => "The Springfield M1892 Krag is a bolt-action rifle that holds five rounds in its internal magazine, and one in its chamber. Its magazine lid allows the wielder to top it up from the side, without opening the bolt, and ejecting the chambered round."
    ],
];
