<?php
return [
    [
        "weapon_name" => "Nitro Express Rifle",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 364,
        "weapon_img" => "weapons/nitro-express-rifle.jpg",
        "ammo_reserve" => 4,
        "bullet_speed" => 550,
        "sway" => 77,
        "effective_range" => 252,
        "reload_time" => 4.8,
        "cycle_time" => 0.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 1015,
        "summary" => "Powerful, side-by-side, big game hunting rifle that can bring down the largest targets at mid-range. Carries limited ammunition."
    ],
    [
        "weapon_name" => "Crossbow",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 247,
        "weapon_img" => "weapons/crossbow.jpeg",
        "ammo_reserve" => 10,
        "bullet_speed" => 150,
        "sway" => 77,
        "effective_range" => 47,
        "reload_time" => 5.3,
        "cycle_time" => 6.1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 73,
        "summary" => "Hand-crafted crossbow that fires powerful bolts. Well suited for covert missions and stealth takedowns, but has a long reload. Bolts can be retrieved and re-used."
    ],
    [
        "weapon_name" => "Romero 77",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 218,
        "weapon_img" => "weapons/romero77.jpeg",
        "ammo_reserve" => 7,
        "bullet_speed" => 450,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 3.4,
        "cycle_time" => 4.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 34,
        "summary" => "Classic break-action shotgun with a long barrel. Good range and power for a shotgun. Has to reload after every shot."
    ],
    [
        "weapon_name" => "Romero 77 Alamo",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 218,
        "weapon_img" => "weapons/romero77.jpeg",
        "ammo_reserve" => 7,
        "bullet_speed" => 450,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 18.2,
        "cycle_time" => 2.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 34,
        "summary" => "Classic break-action shotgun with a long barrel with more shell in the chamber. Good range and power for a shotgun. Has to reload after every shot."
    ],
    [
        "weapon_name" => "Specter 1882",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 210,
        "weapon_img" => "weapons/specter.jpg",
        "ammo_reserve" => 10,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 14.8,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 188,
        "summary" => "Revolutionary pump-action shotgun with long barrel, able to fire shells in rapid succession. Reloading the internal magazine takes time, due to its clunky, unrefined loading sequence."
    ],
    [
        "weapon_name" => "Winfield 1893 Slate",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 203,
        "weapon_img" => "weapons/slate.jpg",
        "ammo_reserve" => 11,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 9.6,
        "cycle_time" => 1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 333,
        "summary" => "An exposed hammer shotgun that replaces lever-action with pump-action, this Winfield Model 93 holds several 12-gauge rounds to cause devastating damage to opponents."
    ],
    [
        "weapon_name" => "Auto-5",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 194,
        "weapon_img" => "weapons/auto-5.jpg",
        "ammo_reserve" => 10,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 10.7,
        "cycle_time" => 0.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 600,
        "summary" => "Prototype long-barreled semi-automatic shotgun with internal four round magazine plus one in the chamber. High power and rate of fire, but strong recoil and short range."
    ],
    [
        "weapon_name" => "Caldwell Rival 78",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 190,
        "weapon_img" => "weapons/caldwellrival.jpg",
        "ammo_reserve" => 10,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 13,
        "reload_time" => 4.7,
        "cycle_time" => 0.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 100,
        "summary" => "Sturdy, break-action, side-by-side shotgun with a medium-length barrel that can destroy all but the toughest targets at close range."
    ],
    [
        "weapon_name" => "Winfield 1887 Terminus",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 190,
        "weapon_img" => "weapons/terminus.jpg",
        "ammo_reserve" => 14,
        "bullet_speed" => 425,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 12.2,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 309,
        "summary" => "Seminal lever-action repeating shotgun. Boasting a balance between power and rate-of-fire, this became an icon of the era. Chamber 5+2 shells."
    ],
    [
        "weapon_name" => "Bomb Lance",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 150,
        "weapon_img" => "weapons/bomblance.jpg",
        "ammo_reserve" => 4,
        "bullet_speed" => 60,
        "sway" => 38,
        "effective_range" => 10,
        "reload_time" => 12.2,
        "cycle_time" => 7.8,
        "light_melee_dmg" => 180,
        "heavy_melee_dmg" => 360,
        "cost" => 199,
        "summary" => "Adapted for combat on land, this explosive harpoon can be fired short distances and deals tremendous damage on direct impact."
    ],
    [
        "weapon_name" => "Sparks LRR",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 149,
        "weapon_img" => "weapons/sparks.jpg",
        "ammo_reserve" => 16,
        "bullet_speed" => 533,
        "sway" => 77,
        "effective_range" => 347,
        "reload_time" => 4,
        "cycle_time" => 5.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 130,
        "summary" => "Renowned, large-bore, single-shot rifle with good sights. Can put down a bison across a prairie."
    ],
    [
        "weapon_name" => "Martini Henry IC1",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 143,
        "weapon_img" => "weapons/martini.jpg",
        "ammo_reserve" => 20,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 334,
        "reload_time" => 2.7,
        "cycle_time" => 4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 122,
        "summary" => "The workhorse rifle of the British Empire, the Martini-Henry IC1 is a single-shot breech-loading rifle that values simplicity and power."
    ],
    [
        "weapon_name" => "Martini Henry IC1 Ironside",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 143,
        "weapon_img" => "weapons/martiniironside.jpg",
        "ammo_reserve" => 20,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 334,
        "reload_time" => 14.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 184,
        "summary" => "This Martini-Henry IC1 features a mechanism carrying five extra cartridges in addition to the one in the rifle's chamber which allows the wielder to replace the spent cartridge in quick succession, transforming the weapon into a makeshift repeating rifle."
    ],
    [
        "weapon_name" => "Mosin-Nagant M1891",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 136,
        "weapon_img" => "weapons/mosin.jpg",
        "ammo_reserve" => 15,
        "bullet_speed" => 615,
        "sway" => 77,
        "effective_range" => 320,
        "reload_time" => 3.7,
        "cycle_time" => 1.9,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 620,
        "summary" => "Modern Imperial Russian bolt-action service rifle with an internal magazine, firing powerful long cartridges. When fully emptied, can be reloaded fast with a five-round stripper clip."
    ],
    [
        "weapon_name" => "Lebel 1886",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 132,
        "weapon_img" => "weapons/lebel.jpg",
        "ammo_reserve" => 15,
        "bullet_speed" => 630,
        "sway" => 77,
        "effective_range" => 311,
        "reload_time" => 18.7,
        "cycle_time" => 1.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 397,
        "summary" => "Modern Imperial Russian bolt-action service rifle with an internal magazine, firing powerful long cartridges. When fully emptied, can be reloaded fast with a five-round stripper clip."
    ],
    [
        "weapon_name" => "Springfield 1866",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 132,
        "weapon_img" => "weapons/springfield.jpg",
        "ammo_reserve" => 25,
        "bullet_speed" => 490,
        "sway" => 77,
        "effective_range" => 212,
        "reload_time" => 3,
        "cycle_time" => 4.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 38,
        "summary" => "A breech-loading rifle with a .50-70 caliber centerfire cartridge, the Springfield 1866 is best known for its quick rate of fire."
    ],
    [
        "weapon_name" => "Vetterli 71 Karabiner",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 130,
        "weapon_img" => "weapons/vetterli.jpg",
        "ammo_reserve" => 26,
        "bullet_speed" => 410,
        "sway" => 77,
        "effective_range" => 204,
        "reload_time" => 12.1,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 105,
        "summary" => "Swiss military, bolt-action carbine with internal magazine. Powerful at medium distances. Reloading is inspired by the Winfield repeater rifle, making it easy to top up ammunition."
    ],
    [
        "weapon_name" => "Berthier Mle 1892",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 130,
        "weapon_img" => "weapons/berthier.jpg",
        "ammo_reserve" => 15,
        "bullet_speed" => 590,
        "sway" => 77,
        "effective_range" => 305,
        "reload_time" => 2.7,
        "cycle_time" => 1.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 330,
        "summary" => "The lighter alternative to the Lebel 1886, the Berthier Mle 1892 is a bolt-action mousqueton that doesn't lose power for the sake of its convenience."
    ],
    [
        "weapon_name" => "Mako 1895 Carbine",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 128,
        "weapon_img" => "weapons/mako.jpg",
        "ammo_reserve" => 14,
        "bullet_speed" => 540,
        "sway" => 77,
        "effective_range" => 302,
        "reload_time" => 13,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 360,
        "summary" => "Long range, lever-action rifle that delivers a powerful punch with long ammo. From a new manufacturer in competition with Winfield."
    ],
    [
        "weapon_name" => "Springfield M1892 Krag",
        "bullet_type_id" => 3,
        "slot_id" => 3,
        "damage" => 126,
        "weapon_img" => "weapons/krag.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 610,
        "sway" => 77,
        "effective_range" => 291,
        "reload_time" => 11.1,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 345,
        "summary" => "The Springfield M1892 Krag is a bolt-action rifle that holds five rounds in its internal magazine, and one in its chamber. Its magazine lid allows the wielder to top it up from the side, without opening the bolt, and ejecting the chambered round."
    ],
    [
        "weapon_name" => "Winfield M1876 Centennial",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 123,
        "weapon_img" => "weapons/centennial.jpg",
        "ammo_reserve" => 21,
        "bullet_speed" => 600,
        "sway" => 77,
        "effective_range" => 180,
        "reload_time" => 15.5,
        "cycle_time" => 1.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 157,
        "summary" => "Powerful repeating rifle chambered for larger ammunition than previous models. The magazine holds 9 rounds."
    ],
    [
        "weapon_name" => "Drilling",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 120,
        "weapon_img" => "weapons/drilling.jpg",
        "ammo_reserve" => 22,
        "bullet_speed" => 530,
        "sway" => 77,
        "effective_range" => 170,
        "reload_time" => 5.3,
        "cycle_time" => 0.6,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 510,
        "summary" => "Two medium rifle barrels combined with a shotgun underbarrel to create an all-round flexible and powerful weapon."
    ],
    [
        "weapon_name" => "Caldwell Marathon",
        "bullet_type_id" => 1,
        "slot_id" => 3,
        "damage" => 113,
        "weapon_img" => "weapons/marathon.jpg",
        "ammo_reserve" => 39,
        "bullet_speed" => 530,
        "sway" => 77,
        "effective_range" => 160,
        "reload_time" => 19.2,
        "cycle_time" => 1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 68,
        "summary" => "Fast-firing pump-action rifle that performs best at mid-range. A clunky reload reduces its flexibility."
    ],
    [
        "weapon_name" => "Frontier 73",
        "bullet_type_id" => 1,
        "slot_id" => 3,
        "damage" => 110,
        "weapon_img" => "weapons/frontier.jpg",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 151,
        "reload_time" => 16.4,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 75,
        "summary" => "Iconic repeating rifle with very large internal magazine, capable of firing compact bullets at rapid speed. Reload is very simple, making an ammo top-up a quick job."
    ],
    [
        "weapon_name" => "Frontier 73C",
        "bullet_type_id" => 1,
        "slot_id" => 3,
        "damage" => 110,
        "weapon_img" => "weapons/frontier.jpg",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 151,
        "reload_time" => 10.2,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 41,
        "summary" => "Lightened repeating rifle with demi-size internal magazine, capable of firing compact bullets at rapid speed."
    ],
    [
        "weapon_name" => "Infantry 73L",
        "bullet_type_id" => 1,
        "slot_id" => 3,
        "damage" => 110,
        "weapon_img" => "weapons/frontier.jpg",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 151,
        "reload_time" => 10.2,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 41,
        "summary" => "Lightened repeating rifle with demi-size internal magazine, capable of firing compact bullets at rapid speed."
    ],
    [
        "weapon_name" => "1865 Carabine",
        "bullet_type_id" => 2,
        "slot_id" => 3,
        "damage" => 145,
        "weapon_img" => "weapons/1865carabine.jpg",
        "ammo_reserve" => 35,
        "bullet_speed" => 400,
        "sway" => 77,
        "effective_range" => 151,
        "reload_time" => 10.2,
        "cycle_time" => 1.2,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 41,
        "summary" => "Lightened repeating rifle with demi-size internal magazine, capable of firing compact bullets at rapid speed."
    ],
    [
        "weapon_name" => "LeMat Mark II Revolver",
        "bullet_type_id" => 1,
        "slot_id" => 1,
        "damage" => 97,
        "weapon_img" => "weapons/lemat.jpg",
        "ammo_reserve" => 27,
        "bullet_speed" => 375,
        "sway" => 128,
        "effective_range" => 80,
        "reload_time" => 15.8,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 83,
        "summary" => "Infamous icon of the Confederacy, this updated model takes nine cartridges in its cylinder. Its second barrel delivers a shotgun blast up close."
    ],
    [
        "weapon_name" => "Caldwell Pax",
        "bullet_type_id" => 2,
        "slot_id" => 1,
        "damage" => 110,
        "weapon_img" => "weapons/pax.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 330,
        "sway" => 128,
        "effective_range" => 87,
        "reload_time" => 11.2,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 80,
        "summary" => "This iconic single-action six round revolver needs no further introduction. Robust, powerful, and accurate, it brought peace to the once lawless West."
    ],
    [
        "weapon_name" => "Scottfield Model 3",
        "bullet_type_id" => 2,
        "slot_id" => 1,
        "damage" => 107,
        "weapon_img" => "weapons/scottfield.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 280,
        "sway" => 128,
        "effective_range" => 85,
        "reload_time" => 9,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 77,
        "summary" => "A classic, single-action break open revolver, the Scottfield has seen both sides of the law. The break action allows for quicker ejecting of spent rounds, meaning a faster overall reload when empty."
    ],
    [
        "weapon_name" => "Conversion",
        "bullet_type_id" => 1,
        "slot_id" => 1,
        "damage" => 104,
        "weapon_img" => "weapons/conversion.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 300,
        "sway" => 128,
        "effective_range" => 85,
        "reload_time" => 11.2,
        "cycle_time" => 1.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 55,
        "summary" => "The Caldwell Conversion Pistol is a single-action six-shot revolver. Slow to reload but sturdy and reliable."
    ],
    [
        "weapon_name" => "Dolch 96",
        "bullet_type_id" => 4,
        "slot_id" => 1,
        "damage" => 97,
        "weapon_img" => "weapons/dolch.jpg",
        "ammo_reserve" => 20,
        "bullet_speed" => 440,
        "sway" => 128,
        "effective_range" => 78,
        "reload_time" => 6,
        "cycle_time" => 0.4,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 690,
        "summary" => "Powerful, German, prototype, semi-automatic pistol with an internal magazine loaded from the top. When fully emptied, it can be reloaded fast with a ten-round stripper clip."
    ],
    [
        "weapon_name" => "Caldwell 92 New Army",
        "bullet_type_id" => 1,
        "slot_id" => 1,
        "damage" => 97,
        "weapon_img" => "weapons/newarmy.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 230,
        "sway" => 128,
        "effective_range" => 80,
        "reload_time" => 9.5,
        "cycle_time" => 0.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 90,
        "summary" => "Fast, light, and easy to handle, this double-action revolver has a distinguished counter-clockwise rotating cylinder that swings out to effortlessly reload its six .38 bullets."
    ],
    [
        "weapon_name" => "Nagant M1895",
        "bullet_type_id" => 1,
        "slot_id" => 1,
        "damage" => 91,
        "weapon_img" => "weapons/nagantpistol.jpg",
        "ammo_reserve" => 28,
        "bullet_speed" => 330,
        "sway" => 128,
        "effective_range" => 74,
        "reload_time" => 12.5,
        "cycle_time" => 1.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 24,
        "summary" => "Modern, Imperial Russian, single-action revolver. Slow to reload. Sacrifices stopping power for an extra bullet in the drum and a higher rate of fire."
    ],
    [
        "weapon_name" => "Nagant M1895 Officer",
        "bullet_type_id" => 1,
        "slot_id" => 1,
        "damage" => 91,
        "weapon_img" => "weapons/nagantpistol.jpg",
        "ammo_reserve" => 16,
        "bullet_speed" => 330,
        "sway" => 128,
        "effective_range" => 74,
        "reload_time" => 12.8,
        "cycle_time" => 0.5,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 96,
        "summary" => "Modern, Imperial Russian, double-action revolver. Though it has a faster rate of fire, the stronger force required to pull the trigger has a negative impact on accuracy."
    ],
    [
        "weapon_name" => "Bornheim No. 3",
        "bullet_type_id" => 1,
        "slot_id" => 1,
        "damage" => 74,
        "weapon_img" => "weapons/bornheim.jpg",
        "ammo_reserve" => 20,
        "bullet_speed" => 380,
        "sway" => 128,
        "effective_range" => 74,
        "reload_time" => 7.4,
        "cycle_time" => 0.2,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 146,
        "summary" => "This early German semi-automatic pistol can release a hail of accurate fire by virtue of its low recoil. Reloads via a five-round magazine, or by topping up rounds individually."
    ],
    [
        "weapon_name" => "Cavalry Saber",
        "bullet_type_id" => 5,
        "slot_id" => 1,
        "damage" => 82,
        "weapon_img" => "weapons/saber.jpg",
        "ammo_reserve" => 1,
        "bullet_speed" => 0,
        "sway" => 0,
        "effective_range" => 1.5,
        "reload_time" => 0,
        "cycle_time" => 0,
        "light_melee_dmg" => 82,
        "heavy_melee_dmg" => 168,
        "cost" => 50,
        "summary" => "Regulation cavalry saber in use since the Civil War. Lightweight with good reach."
    ],
    [
        "weapon_name" => "Machete",
        "bullet_type_id" => 5,
        "slot_id" => 1,
        "damage" => 90,
        "weapon_img" => "weapons/machete.jpg",
        "ammo_reserve" => 1,
        "bullet_speed" => 0,
        "sway" => 0,
        "effective_range" => 1,
        "reload_time" => 0,
        "cycle_time" => 0,
        "light_melee_dmg" => 90,
        "heavy_melee_dmg" => 150,
        "cost" => 30,
        "summary" => "Used both for cutting through undergrowth and limbs, a machete is a reliable weapon to forge a path."
    ],
    [
        "weapon_name" => "Baseball Bat",
        "bullet_type_id" => 5,
        "slot_id" => 1,
        "damage" => 90,
        "weapon_img" => "weapons/bat.jpg",
        "ammo_reserve" => 1,
        "bullet_speed" => 0,
        "sway" => 0,
        "effective_range" => 1,
        "reload_time" => 0,
        "cycle_time" => 0,
        "light_melee_dmg" => 90,
        "heavy_melee_dmg" => 153,
        "cost" => 40,
        "summary" => "The Baseball Bat swings intuitively and easily, delivering a solid blow."
    ],
    [
        "weapon_name" => "Katana",
        "bullet_type_id" => 5,
        "slot_id" => 1,
        "damage" => 165,
        "weapon_img" => "weapons/katana.jpg",
        "ammo_reserve" => 1,
        "bullet_speed" => 0,
        "sway" => 0,
        "effective_range" => 1,
        "reload_time" => 0,
        "cycle_time" => 0,
        "light_melee_dmg" => 165,
        "heavy_melee_dmg" => 280,
        "cost" => 115,
        "summary" => "A two-handed sword refined over hundreds of years to slice and pierce even the sturdiest armor, making human flesh effortless to rend. Special attack enabled with Martialist Trait."
    ],
    [
        "weapon_name" => "Hunting Bow",
        "bullet_type_id" => 4,
        "slot_id" => 2,
        "damage" => 227,
        "weapon_img" => "weapons/bow.jpg",
        "ammo_reserve" => 17,
        "bullet_speed" => 150,
        "sway" => 87,
        "effective_range" => 20,
        "reload_time" => 0.6,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 57,
        "summary" => "Able to pierce through flesh and bone at a great distance, the Hunting Bow will make quick, stealthy work of monsters and men."
    ],
    [
        "weapon_name" => "Combat Axe",
        "bullet_type_id" => 5,
        "slot_id" => 1,
        "damage" => 165,
        "weapon_img" => "weapons/axe.jpg",
        "ammo_reserve" => 1,
        "bullet_speed" => 0,
        "sway" => 0,
        "effective_range" => 1,
        "reload_time" => 0,
        "cycle_time" => 0,
        "light_melee_dmg" => 165,
        "heavy_melee_dmg" => 330,
        "cost" => 40,
        "summary" => "A heavy two-handed melee weapon that can split open the toughest of enemies with ease."
    ],
    [
        "weapon_name" => "Railroad Hammer",
        "bullet_type_id" => 5,
        "slot_id" => 1,
        "damage" => 104,
        "weapon_img" => "weapons/hammer.jpg",
        "ammo_reserve" => 1,
        "bullet_speed" => 0,
        "sway" => 0,
        "effective_range" => 1,
        "reload_time" => 0,
        "cycle_time" => 0,
        "light_melee_dmg" => 153,
        "heavy_melee_dmg" => 261,
        "cost" => 45,
        "summary" => "Large mallet designed to hammer railroad spikes into their tracks, repurposed to hammer heads into the dirt."
    ],
    [
        "weapon_name" => "Haymaker",
        "bullet_type_id" => 3,
        "slot_id" => 2,
        "damage" => 120,
        "weapon_img" => "weapons/haymaker.jpg",
        "ammo_reserve" => 18,
        "bullet_speed" => 530,
        "sway" => 128,
        "effective_range" => 112,
        "reload_time" => 21.8,
        "cycle_time" => 1.3,
        "light_melee_dmg" => 13,
        "heavy_melee_dmg" => 31,
        "cost" => 370,
        "summary" => "Two-handed advancement on the LeMat Mark II that trades speed for power, and uses Long Ammo."
    ],
];
