<?php
return [
    [
        "weapon_name" => "Nitro Express Rifle",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 364,
        "weapon_img" => "weapons/nitro-express-rifle.jpg",
        "ammo_reserve" => 4,
        "bullet_speed" => 550,
        "sway" => 77,
        "effective_range" => 252,
        "reload_time" => 4.8,
        "cycle_time" => 0.7,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 1015,
        "summary" => "Powerful, side-by-side, big game hunting rifle that can bring down the largest targets at mid-range. Carries limited ammunition."
    ],
    [
        "weapon_name" => "Crossbow",
        "bullet_type_id" => 4,
        "slot_id" => 3,
        "damage" => 247,
        "weapon_img" => "weapons/crossbow.jpeg",
        "ammo_reserve" => 10,
        "bullet_speed" => 150,
        "sway" => 77,
        "effective_range" => 47,
        "reload_time" => 5.3,
        "cycle_time" => 6.1,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 73,
        "summary" => "Hand-crafted crossbow that fires powerful bolts. Well suited for covert missions and stealth takedowns, but has a long reload. Bolts can be retrieved and re-used."
    ],
    [
        "weapon_name" => "Romero 77",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 218,
        "weapon_img" => "weapons/romero77.jpeg",
        "ammo_reserve" => 7,
        "bullet_speed" => 450,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 3.4,
        "cycle_time" => 4.3,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 34,
        "summary" => "Classic break-action shotgun with a long barrel. Good range and power for a shotgun. Has to reload after every shot."
    ],
    [
        "weapon_name" => "Romero 77 Alamo",
        "bullet_type_id" => 5,
        "slot_id" => 3,
        "damage" => 218,
        "weapon_img" => "weapons/romero77.jpeg",
        "ammo_reserve" => 7,
        "bullet_speed" => 450,
        "sway" => 77,
        "effective_range" => 14,
        "reload_time" => 18.2,
        "cycle_time" => 2.8,
        "light_melee_dmg" => 27,
        "heavy_melee_dmg" => 54,
        "cost" => 34,
        "summary" => "Classic break-action shotgun with a long barrel with more shell in the chamber. Good range and power for a shotgun. Has to reload after every shot."
    ],
];
